repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black
      additional_dependencies: ['click==8.0.4']
      files: "\\.(py)$"
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: ["--profile", "black"]
      files: "\\.(py)$"
